//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Talpa_Api.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Talpa_Api.Localization.LocalizationStrings", typeof(LocalizationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates must contain at least one date..
        /// </summary>
        public static string CreatePollDateCountWrong {
            get {
                return ResourceManager.GetString("CreatePollDateCountWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll must have a minimum of 1 suggestion and a maximum of 3..
        /// </summary>
        public static string CreatePollSuggestionCountWrong {
            get {
                return ResourceManager.GetString("CreatePollSuggestionCountWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image is invalid..
        /// </summary>
        public static string ImageInvalid {
            get {
                return ResourceManager.GetString("ImageInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image is too large..
        /// </summary>
        public static string ImageTooLarge {
            get {
                return ResourceManager.GetString("ImageTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll has ended..
        /// </summary>
        public static string PollHasEnded {
            get {
                return ResourceManager.GetString("PollHasEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll not found..
        /// </summary>
        public static string PollNotFound {
            get {
                return ResourceManager.GetString("PollNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion not found..
        /// </summary>
        public static string SuggestionNotFound {
            get {
                return ResourceManager.GetString("SuggestionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion is too similar to an existing suggestion..
        /// </summary>
        public static string SuggestionTooSimilar {
            get {
                return ResourceManager.GetString("SuggestionTooSimilar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag already exists..
        /// </summary>
        public static string TagAlreadyExists {
            get {
                return ResourceManager.GetString("TagAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag not found..
        /// </summary>
        public static string TagNotFound {
            get {
                return ResourceManager.GetString("TagNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team already has an active poll..
        /// </summary>
        public static string TeamAlreadyActivePoll {
            get {
                return ResourceManager.GetString("TeamAlreadyActivePoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team already exists..
        /// </summary>
        public static string TeamAlreadyExists {
            get {
                return ResourceManager.GetString("TeamAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team not found..
        /// </summary>
        public static string TeamNotFound {
            get {
                return ResourceManager.GetString("TeamNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists..
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has already voted in this poll..
        /// </summary>
        public static string UserAlreadyVoted {
            get {
                return ResourceManager.GetString("UserAlreadyVoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote not found..
        /// </summary>
        public static string VoteNotFound {
            get {
                return ResourceManager.GetString("VoteNotFound", resourceCulture);
            }
        }
    }
}
